server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fyp_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: fyp_db
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace​
